#!/usr/bin/env python3
"""
Regenerate RUN_CONFIG.md from source. The flag table is DERIVED, never hand-typed,
so it cannot drift from the simulator.

  python3 tools/dump_run_config.py            # rewrite RUN_CONFIG.md
  python3 tools/dump_run_config.py --check    # exit 1 if stale or a flag lacks rationale

Rationale (why a flag is / isn't used) is human knowledge and lives in
tools/flag_rationale.json. Any flag missing from it is reported as a gap.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "scratch" / "mptd_pqs_sdvn"
OUT  = ROOT / "RUN_CONFIG.md"
RAT  = Path(__file__).parent / "flag_rationale.json"

# Scan EVERY header: routing_test (the #1 trap) is declared in 07_socket_layer.h,
# not in any config header. Restricting the scan is how that default stayed invisible.
HEADERS = sorted(f.name for f in SRC.glob("*.h"))

def read(p):
    return (SRC / p).read_text(errors="ignore")

def parse_flags():
    """(flag, bound_variable) from cmd.AddValue(...), tolerant of line breaks."""
    blob = read("12_main.h")
    out = []
    for m in re.finditer(r'cmd\.AddValue\s*\(\s*"([^"]+)"\s*,', blob):
        name = m.group(1)
        # third argument = last comma-separated token before the closing paren
        tail, depth, i = "", 1, m.end()
        while i < len(blob) and depth:
            c = blob[i]
            depth += (c == "(") - (c == ")")
            if depth: tail += c
            i += 1
        parts = [a.strip() for a in re.split(r',(?![^"]*"\s*[,)])', tail)]
        var = parts[-1].strip() if parts else ""
        var = re.sub(r'\s+', ' ', var)
        out.append((name, var))
    return out

def parse_defaults():
    """variable -> literal initialiser, scanned across the headers."""
    d = {}
    for h in HEADERS:
        for m in re.finditer(
            r'^\s*(?:static\s+|inline\s+|constexpr\s+)*'
            r'(?:bool|int|unsigned|uint32_t|double|float|std::string)\s+'
            r'(\w+)\s*=\s*([^;{]+);', read(h), re.M):
            d.setdefault(m.group(1), m.group(2).strip())
    return d

def render():
    rat = json.loads(RAT.read_text())
    canonical = rat["canonical_run"]
    notes = rat["flags"]
    flags = parse_flags()
    defaults = parse_defaults()
    missing = [f for f, _ in flags if f not in notes]

    L = []
    A = L.append
    A("<!-- GENERATED by tools/dump_run_config.py — DO NOT EDIT BY HAND.")
    A("     Flag names/defaults come from scratch/mptd_pqs_sdvn/. Rationale comes")
    A("     from tools/flag_rationale.json. Edit those, then regenerate. -->")
    A("")
    A("# Simulation run configuration — flags, defaults, and why")
    A("")
    A(f"Derived from `scratch/mptd_pqs_sdvn/`. {len(flags)} CLI flags found in `12_main.h`.")
    A("")
    A("## The canonical run")
    A("")
    A("This is the configuration that produced the currently reported D1/D4/D6 results.")
    A("")
    A("```bash")
    A(canonical["command"].rstrip())
    A("```")
    A("")
    A("| arm | flags |")
    A("|---|---|")
    for arm, f in canonical["arms"].items():
        A(f"| {arm} | `{f}` |")
    A("")
    A("**Verify before every run:**")
    A("")
    A("```bash")
    A(canonical["preflight"].rstrip())
    A("```")
    A("")
    A("## Traps — read before running anything")
    A("")
    A("| trap | detail |")
    A("|---|---|")
    for t in rat["traps"]:
        A(f"| {t['trap']} | {t['detail']} |")
    A("")
    A("## Flags in the reported runs")
    A("")
    A("| flag | default | set to | why |")
    A("|---|---|---|---|")
    for f, v in flags:
        n = notes.get(f)
        if not n or n["status"] != "used": continue
        A(f"| `--{f}` | `{defaults.get(v,'?')}` | `{n.get('value','')}` | {n['why']} |")
    A("")
    A("## Flags deliberately NOT used")
    A("")
    A("| flag | default | why not used | when it SHOULD be used |")
    A("|---|---|---|---|")
    for f, v in flags:
        n = notes.get(f)
        if not n or n["status"] not in ("unused", "broken"): continue
        mark = "❌ **BROKEN** — " if n["status"] == "broken" else ""
        A(f"| `--{f}` | `{defaults.get(v,'?')}` | {mark}{n['why']} | {n.get('when','—')} |")
    A("")
    A("## Sweep / experiment flags (used only by the named experiment)")
    A("")
    A("| flag | default | belongs to |")
    A("|---|---|---|")
    for f, v in flags:
        n = notes.get(f)
        if not n or n["status"] != "sweep": continue
        A(f"| `--{f}` | `{defaults.get(v,'?')}` | {n['why']} |")
    A("")
    if missing:
        A("## ⚠️ UNDOCUMENTED FLAGS")
        A("")
        A("These exist in `12_main.h` but have no entry in `tools/flag_rationale.json`.")
        A("Add one — an undocumented flag is how a run gets silently misconfigured.")
        A("")
        for f in missing:
            A(f"- `--{f}`")
        A("")
    return "\n".join(L) + "\n", missing

def main():
    text, missing = render()
    check = "--check" in sys.argv
    if check:
        cur = OUT.read_text() if OUT.exists() else ""
        stale = cur != text
        if stale: print(f"STALE: {OUT.name} does not match source. Run: python3 tools/dump_run_config.py")
        for f in missing: print(f"UNDOCUMENTED FLAG: --{f}")
        sys.exit(1 if (stale or missing) else 0)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    for f in missing: print(f"  UNDOCUMENTED: --{f}")

if __name__ == "__main__":
    main()
